WebMVC/Controllers/EnvioController.cs
using CasoUsoCompartida.DTOs.Envios;
using CasoUsoCompartida.DTOs.EtapaSeguimiento;
using CasoUsoCompartida.DTOs.Usuarios;
using CasoUsoCompartida.InterfacesCU;
using CasoUsoCompartida.DTOs;
using LogicaAplicacion.CasosUso.Envios;
using LogicaNegocio.Entidades.Envios;
using LogicaNegocio.Entidades.Usuarios.Usuario;
using LogicaNegocio.Excepciones.AgenciaException;
using LogicaNegocio.Excepciones.EnvioExceptions;
using LogicaNegocio.Excepciones.Envios;
using LogicaNegocio.Excepciones.EtapaSeguimientoExceptions;
using LogicaNegocio.Vo.Envio;
using Microsoft.AspNetCore.Authorization;
using WebMVC.Filtros;
using Microsoft.AspNetCore.Mvc;
using CasoUsoCompartida.DTOS.Envios;

namespace WebMVC.Controllers
{
    [UsuarioLogueado]
    public class EnvioController : Controller
    {
        private IGetAll<EnvioListadoDto> _getAll;
        private IAdd<CrearEnvioDto> _add;
        private IFinalizar _finalizar;
        private IAdd<CrearComentarioDto> _addComentario;
        private IGetAll<AgenciaListadoDto> _agencias;

        public EnvioController(IGetAll<EnvioListadoDto> getAll, IAdd<CrearEnvioDto> add, IFinalizar finalizar, IAdd<CrearComentarioDto> comentario, IGetAll<AgenciaListadoDto> agencias)
        {
            _getAll = getAll;
            _add = add;
            _finalizar = finalizar;
            _addComentario = comentario;
            _agencias = agencias;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ListadoEnvios(
            string nroTracking,
            DateTime? fechaDesde,
            DateTime? fechaHasta)

        {
            IEnumerable<EnvioListadoDto> listaEnvios = _getAll.Execute();


            // 2) Aplicas filtros si vienen
            if (!string.IsNullOrWhiteSpace(nroTracking))
                listaEnvios = listaEnvios.Where(e =>
                    e.NroTracking.Contains(nroTracking, StringComparison.OrdinalIgnoreCase));

            if (fechaDesde.HasValue)
                listaEnvios = listaEnvios.Where(e => e.FechaCreacion >= fechaDesde.Value);

            if (fechaHasta.HasValue)
                listaEnvios = listaEnvios.Where(e => e.FechaCreacion <= fechaHasta.Value);

            // 3) Pasas los filtros a la vista para volver a mostrarlos
            ViewBag.NroTracking = nroTracking;
            ViewBag.FechaDesde = fechaDesde?.ToString("yyyy-MM-dd");
            ViewBag.FechaHasta = fechaHasta?.ToString("yyyy-MM-dd");

            return View(listaEnvios);
        }

        // Acción para dar de alta un envio
        [HttpGet]
        public IActionResult Crear()
        {
            var listadoAgencias = _agencias.Execute();
            ViewBag.CorreoEmpleado = HttpContext.Session.GetString("CorreoEmpleado");
            ViewData["ListadoAgencias"] = listadoAgencias;
            return View();
        }

        [HttpPost]
        public IActionResult Crear(CrearEnvioDto envioDto)
        {
            try
            {

                _add.Execute(envioDto);
                return RedirectToAction("ListadoEnvios");
            }
            catch (TipoEnvioException)
            {
                ViewBag.Message = "El Nombre es incorrecto";
            }
            catch (CorreoException)
            {
                ViewBag.Message = "El Correo ingresado no esta registrado como cliente";
                return View();
            }
            catch (PesoException)
            {
                ViewBag.Message = "El Peso debe ser un número positivo";
            }
            catch (LugarRetiroException)
            {
                ViewBag.Message = "Debes seleccionar un lugar de retiro";
            }
            catch (DireccionException)
            {
                ViewBag.Message = "La Dirección es un campo que no puede estar vacio";
            }
            catch (NombreAgenciaExeption)
            {
                ViewBag.Message = "No existe esa Agencia";
            }

            ViewBag.CorreoEmpleado = envioDto.CorreoEmpleado;
            return View();

        }

        [HttpGet]
        public IActionResult Finalizar(int id) 
        {
            try
            {
                _finalizar.Execute(id);

                return RedirectToAction("ListadoEnvios");
            }
            catch (TipoEnvioException)
            {
                ViewBag.Message = "Error Al finalizar envio";
            }
            return RedirectToAction("ListadoEnvios");
        }

        [HttpGet]
        public IActionResult AgregarComentario(int envioId, string nroTracking)
        {
            var empleadoCorreo = HttpContext.Session.GetString("CorreoEmpleado");

            var dto = new CrearComentarioDto(
                     IdEnvio: envioId,
                     NroTracking: nroTracking,
                     CorreoEmpleado: empleadoCorreo,
                     Comentario: string.Empty
                );

            return View(dto);
        }


        [HttpPost]
        public IActionResult AgregarComentario(CrearComentarioDto comentarioDto)
        {
            try
            {

                _addComentario.Execute(comentarioDto);
                return RedirectToAction("ListadoEnvios");
            }

            catch (ComentarioException)
            {
                ViewBag.Message = "El comentario no puede estar vacío";
                return View();
            }
        }

    }
}

WebMVC/Controllers/UsuarioController.cs
using CasoUsoCompartida.DTOs.Envios;
using CasoUsoCompartida.DTOs.Usuarios;
using CasoUsoCompartida.InterfacesCU;
using LogicaAplicacion.CasosUso.Usuarios;
using LogicaNegocio.Entidades.Envios;
using LogicaNegocio.Entidades.Usuarios.Empleados;
using LogicaNegocio.Excepciones.UsuarioExceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Filtros;

namespace WebMVC.Controllers
{
    public class UsuarioController : Controller
    {
        //inyectar caso de uso de usuario
        private ILogin<LoginRespuestaDto> _login;
        private IGetAll<UsuarioListadoDto> _getAll;
        private IGetById<UsuarioDto> _getById;
        private IGetById<CrearUsuarioDto> _getByIdEditar;
        private IAdd<CrearUsuarioDto> _add;
        private IRemove _remove;
        private IUpdate<CrearUsuarioDto> _update;
        private IGetByEmail<UsuarioDto> _getByEmail;

        public UsuarioController(ILogin<LoginRespuestaDto> login, IGetAll<UsuarioListadoDto> getAll, IAdd<CrearUsuarioDto> add, IRemove remove, IUpdate<CrearUsuarioDto> update, IGetById<UsuarioDto> getById, IGetById<CrearUsuarioDto> getByIdEditar, IGetByEmail<UsuarioDto> getByEmail)
        {
            _login = login;
            _getAll = getAll;
            _add = add;
            _remove = remove;
            _update = update;
            _getById = getById;
            _getByIdEditar = getByIdEditar;
            _getByEmail = getByEmail;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        // POST: /Usuario/Login
        [HttpPost]
        public IActionResult Login(LoginEntradaDto model)
        {
                var result = _login.Execute(model);

                if (!result.Autenticado)
                {
                    ViewBag.Error = result.Mensaje;
                    return View(model);
                }

                // Obtenemos el usuario para preguntar
                var usuario = _getByEmail.Execute(model.Correo);

                if (usuario.Discriminator.ToLower() == "admin")
                {
                    HttpContext.Session.SetString("Rol", "Admin");
                }
                else
                {
                    HttpContext.Session.SetString("Rol", "NoAdmin");
                }

                // Si todo OK, guardamos la sesión:
                HttpContext.Session.SetString("Logueado", "true");
                HttpContext.Session.SetString("CorreoEmpleado", model.Correo);

                return RedirectToAction("Index", "Home");
        }

        [UsuarioLogueado]
        [HttpGet]
        public IActionResult Gestion()
        {
            TempData["Rol"] = HttpContext.Session.GetString("Rol");
            IEnumerable<UsuarioListadoDto> usuarios = _getAll.Execute();
            var listaUsuarios = usuarios.OrderBy(e => e.Discriminator).ToList();
            return View(listaUsuarios);
        }


        // Acción para dar de alta un usuario
        [UsuarioLogueado]
        [AdminAutorizado]
        [HttpGet]
        public IActionResult Crear()
        {
            var model = new CrearUsuarioDto(
                                Id: 0,
                                Nombre: "",
                                Apellido: "",
                                Correo: "",
                                Clave: "",
                                Telefono: "",
                                CorreoResponsable: HttpContext.Session.GetString("CorreoEmpleado")
                            );
            return View(model);
        }

        [UsuarioLogueado]
        [AdminAutorizado]
        [HttpGet]
        public IActionResult Borrar(int id)
        {
            try
            {
                var dtoEliminar = new CrearUsuarioDto(
                                                Id: id,
                                                Nombre: "",
                                                Apellido: "",
                                                Correo: "",
                                                Clave: "",
                                                Telefono: "",
                                                CorreoResponsable: HttpContext.Session.GetString("CorreoEmpleado")
                                );
                _remove.Execute(dtoEliminar);
                return RedirectToAction("Gestion");
            }
            catch (EmpleadoConEnvioException)
            {

                TempData["Message"] = "El Funcionario que desea borrar ya ha creado envios";
                return RedirectToAction("Gestion");

            }

        }

        [UsuarioLogueado]
        [AdminAutorizado]
        [HttpGet]
        public IActionResult Editar(int id)
        {
            // Se llama al caso de uso GetById para obtener los datos actuales
            var usuarioDto = _getByIdEditar.Execute(id);
            return View(usuarioDto);
        }

        [HttpPost]
        [AdminAutorizado]
        public IActionResult Editar(int id, CrearUsuarioDto usuarioDto)
        {
            try
            {
                var dtoModificar = new CrearUsuarioDto(
                    Id: id,
                    Nombre: usuarioDto.Nombre,
                    Apellido: usuarioDto.Apellido,
                    Correo: usuarioDto.Correo,
                    Clave: usuarioDto.Clave,
                    Telefono: usuarioDto.Telefono,
                    CorreoResponsable: HttpContext.Session.GetString("CorreoEmpleado")
    );
                _update.Execute(id, dtoModificar);
                return RedirectToAction("Gestion");
            }
            catch (NombreException)
            {
                ViewBag.Message = "El Nombre es incorrecto";
            }
            catch (ApellidoException)
            {
                ViewBag.Message = "El Apellido es incorrecto";
            }
            catch (CorreoException)
            {
                ViewBag.Message = "El Correo es incorrecto";
            }
            catch (ClaveException)
            {
                ViewBag.Message = "La Clave es incorrecta";
            }
            catch (TelefonoException)
            {
                ViewBag.Message = "El Telefono es incorrecto";
            }


            return View();
        }

        [AdminAutorizado]
        [HttpPost]
        public IActionResult Crear(CrearUsuarioDto usuarioDto)
        {
            try
            { 
                _add.Execute(usuarioDto);
                return RedirectToAction("Gestion");
            }
            catch (NombreException)
            {
                ViewBag.Message = "El Nombre es incorrecto";
            }
            catch (ApellidoException)
            {
                ViewBag.Message = "El Apellido es incorrecto";
            }
            catch (CorreoException)
            {
                ViewBag.Message = "El Correo es incorrecto";
            }
            catch (ClaveException)
            {
                ViewBag.Message = "La clave debe tener al menos 6 caracteres e incluir letras, números y al menos uno de los siguientes caracteres especiales: + . #";
            }
            catch (TelefonoException)
            {
                ViewBag.Message = "El Telefono es incorrecto";
            }
            catch (YaExisteUsuarioException)
            {
                ViewBag.Message = "El Usuario Ya Existe";
            }

            return View();

        }


        // Acción para cerrar sesión
        [HttpPost]
        public IActionResult Logout()
        {
            // Eliminar la sesión
            HttpContext.Session.Remove("Logueado");

            // Redirigir al inicio o a la página de login
            return RedirectToAction("Login");
        }


    }
}

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @* Mostrar "Iniciar sesión" solo si el usuario NO está logueado *@
                        @if (Context.Session.GetString("Logueado") != "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">
                                    Iniciar sesión
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <form asp-controller="Usuario" asp-action="Logout" method="post" class="d-inline">
                                    <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                                </form>
                            </li>
                        }


                        @* Mostrar el enlace de gestión si el usuario está logueado *@
                        @if (Context.Session.GetString("Logueado") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Gestion">
                                    Gestión de empleados
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Envio" asp-action="ListadoEnvios">
                                    Ver Envíos
                                </a>
                            </li>

                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>